# Generated by Django 2.1.5 on 2019-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190126_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
